### ISSUE TITLE
Undefined class constant 'VERSION'

### ISSUE THREAD

**Issue by RonnieVisser** [zend-server-plugins/Laravel#2]
Following error occurs when installing for Laravel.

Undefined class constant 'VERSION' in /opt/zray/runtime/var/plugins/Laravel/zray/zray.php on line 41

Any thoughts on this?

Ronnie

**Comment by idangozlan** [comment]
Can you be more specific please? which version of Laravel are you trying to use? when it exactly reproduce?

**Comment by RonnieStepOrange** [comment]
I am using Laravel 5.1.10 LTS. I get this error running my codeception tests.

**Comment by idangozlan** [comment]
Thanks for your feedback,

Can you supply reproducible code please?

**Comment by RonnieStepOrange** [comment]
I run from laravel root the following command: vendor/bin/codecept run functional

this is the error:
Codeception PHP Testing Framework v2.1.2
Powered by PHPUnit 4.8.6 by Sebastian Bergmann and contributors.
PHP Fatal error:  Undefined class constant 'VERSION' in /opt/zray/runtime/var/plugins/Laravel/zray/zray.php on line 41

**Comment by idangozlan** [comment]
Hi Ronnie,

Can you supply reproducible in zip file please?

Thanks.

**Comment by RonnieStepOrange** [comment]
what do you need in this file?

**Comment by idangozlan** [comment]
A sample code which will reproduce this issue, since we are not able to reproduce it.

**Comment by RonnieStepOrange** [comment]
I'm sorry for my late response but i cannot give my source code.

**Comment by idangozlan** [comment]
Any reproducable code sample?

**Comment by RonnieStepOrange** [comment]
No it's just a upgraded version from 5 to 5.1

full stack trace of error is:
PHP Fatal error:  Undefined class constant 'VERSION' in /opt/zray/runtime/var/plugins/Laravel/zray/zray.php on line 55
PHP Stack trace:
PHP   1. {main}() /home/vagrant/Code/StepOrange/Finance/vendor/codeception/codeception/codecept:0
PHP   2. Symfony\Component\Console\Application->run() /home/vagrant/Code/StepOrange/Finance/vendor/codeception/codeception/codecept:28
PHP   3. Symfony\Component\Console\Application->doRun() /home/vagrant/Code/StepOrange/Finance/vendor/symfony/console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand() /home/vagrant/Code/StepOrange/Finance/vendor/symfony/console/Application.php:195
PHP   5. Symfony\Component\Console\Command\Command->run() /home/vagrant/Code/StepOrange/Finance/vendor/symfony/console/Application.php:878
PHP   6. Codeception\Command\Run->execute() /home/vagrant/Code/StepOrange/Finance/vendor/symfony/console/Command/Command.php:259
PHP   7. Codeception\Command\Run->runSuites() /home/vagrant/Code/StepOrange/Finance/vendor/codeception/codeception/src/Codeception/Command/Run.php:189
PHP   8. Codeception\Codecept->run() /home/vagrant/Code/StepOrange/Finance/vendor/codeception/codeception/src/Codeception/Command/Run.php:262
PHP   9. Codeception\Codecept->runSuite() /home/vagrant/Code/StepOrange/Finance/vendor/codeception/codeception/src/Codeception/Codecept.php:172
PHP  10. Codeception\SuiteManager->initialize() /home/vagrant/Code/StepOrange/Finance/vendor/codeception/codeception/src/Codeception/Codecept.php:198
PHP  11. Codeception\Module\Laravel5->_initialize() /home/vagrant/Code/StepOrange/Finance/vendor/codeception/codeception/src/Codeception/SuiteManager.php:81
PHP  12. Codeception\Lib\Connector\Laravel5->__construct() /home/vagrant/Code/StepOrange/Finance/vendor/codeception/codeception/src/Codeception/Module/Laravel5.php:108
PHP  13. Codeception\Lib\Connector\Laravel5->initialize() /home/vagrant/Code/StepOrange/Finance/vendor/codeception/codeception/src/Codeception/Lib/Connector/Laravel5.php:31
PHP  14. Illuminate\Foundation\Http\Kernel->bootstrap() /home/vagrant/Code/StepOrange/Finance/vendor/codeception/codeception/src/Codeception/Lib/Connector/Laravel5.php:91
PHP  15. Illuminate\Foundation\Application->bootstrapWith() /home/vagrant/Code/StepOrange/Finance/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:222
PHP  16. Illuminate\Foundation\Bootstrap\BootProviders->bootstrap() /home/vagrant/Code/StepOrange/Finance/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:203
PHP  17. ZRay\Laravel->laravelBeforeRun() /home/vagrant/Code/StepOrange/Finance/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:17

**Comment by idangozlan** [comment]
Hi,

The new version (1.0.4) contain fixes for this issue, please let us know if this issue / another issue appear again.
Download: https://github.com/zend-server-plugins/Laravel/archive/1.0.4.tar.gz
Replace with current Laravel plugin dir (For Z-Ray Standalone is: /opt/zray/runtime/var/plugins/Laravel/)

Thanks for your feedback.
